info.component: Abalon Webdav

server:
  port: 26536
  use-forward-headers: true

management:
  security:
    enabled: false

endpoints:
  sensitive: true
  info.sensitive: false
  health.sensitive: false

#spring:
#  zipkin:
#    enabled: true
#    baseUrl: http://localhost:9411
#  sleuth:
#    enabled: true
#    sampler.percentage: 1.0

logging:
  level:
    root: WARN

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO

    #org.springframework.security.oauth2: DEBUG

    se.abalon: DEBUG

#springfox.documentation.swagger.v2.path: /api-docs

---
spring:
  profiles: docker
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: test, apidoc, local


---
spring:
  profiles: production
